### ISSUE TITLE
Autosplitter only splits each batch once

### ISSUE THREAD

**Issue by badBlackShark** [henktools/autosplitters#8]
As I saw, basically all of the autosplitter was rewritten. I did some 100% runs with it, and during one session it only splits each batch once. It only works again when you restart (idk if game or LiveSplit, I just did both).

E.g. you reset after The Classic, then the Back in Action split will not work anymore, but all others will.

**Comment by faultyserver** [comment]
https://github.com/Voxelse/ASLScripts/blob/master/Livesplit.ActionHenk/Livesplit.ActionHenk.asl has taken over maintenance of this. I meant to archive this as part of that migration but forgot.
